version: '3'
services:
  api:
    container_name: ${API_NAME}
    ports:
      - '${API_PORT}:${API_PORT}'
    build:
      dockerfile: ${API_DOCKERFILE}
      context: .
    working_dir: /api
    environment:
      - API_ENVIRONMENT=${API_ENVIRONMENT}
      # DATABASE
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      # APP
      - API_PORT=${API_PORT}
      - APP_NAME=${API_NAME}
      - UI_URL=${UI_URL}
      - API_URL=${API_URL}
      - SOCKET_URL={SOCKET_URL}
      - ASSETS_URL=${ASSETS_URL}
      - FUEL_PROVIDER=${FUEL_PROVIDER}
      # ASSETS
      - COIN_MARKET_CAP_API_KEY=${COIN_MARKET_CAP_API_KEY}
      - GAS_LIMIT=${GAS_LIMIT}
      - MAX_FEE=${MAX_FEE}
      # TOKENS
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - API_TOKEN_SECRET=${API_TOKEN_SECRET}
      - API_TOKEN_SECRET_IV=${API_TOKEN_SECRET_IV}
      # AWS
      - AWS_SMTP_USER=${AWS_SMTP_USER}
      - AWS_SMTP_PASS=${AWS_SMTP_PASS}
      - AWS_SMTP_HOST=${AWS_SMTP_HOST}
      # EMAIL
      - EMAIL_FROM=${EMAIL_FROM}
      - MAIL_TESTING_NOTIFICATIONS=${MAIL_TESTING_NOTIFICATIONS}
